webapp:
  name: "webapp"
  image: sev1tech/webapp
  imageTag: latest
  env:
  port: 80
  readinessProbe:
    path: /
    initialDelaySeconds: 3
    timeoutSeconds: 3
  livenessProbe:
    path: /
    initialDelaySeconds: 30
    timeoutSeconds: 3
  resources:
    memory:
      request: 256Mi
      limit: 512Mi

personService:
  name: "person-service"
  image: sev1tech/person-service
  imageTag: latest
  env:
  port: 8080
  readinessProbe:
    path: /persons
    initialDelaySeconds: 30
    timeoutSeconds: 3
  livenessProbe:
    path: /persons
    initialDelaySeconds: 30
    timeoutSeconds: 3
  resources:
    memory:
      request: 256Mi
      limit: 512Mi
  database:
    host: postgres
    port: 5432
    name: postgres
    secretName: postgres-secret

postgresql:
  fullnameOverride: postgres
  auth:
    username: sev1_user
    password: interview@2023
    database: sev1_chlg
    postgresPassword: postgres
