
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webapp.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: web
    port: 80
    targetPort: {{ .Values.webapp.port }}
  selector:
    app: {{ .Values.webapp.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.personService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: web
    port: 8080
    targetPort: {{ .Values.personService.port }}
  selector:
    app: {{ .Values.personService.name }}
