---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - image: geocent-code-challenge/webapp
        imagePullPolicy: Never
        name: app
        workingDir: /app
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: core-configmap
        - secretRef:
            name: core-secrets
      restartPolicy: Always
